title: Saaket Agashe
email: saagashe@ucsc.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://saa1605.github.io" # the base hostname & protocol for your site
twitter_username: saa1605
github_username: saa1605 

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing and publishing
exclude:
  - Gemfile
  - Gemfile.lock
