# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'Saaket Agashe'
description:      'Computer Science student interested in Machine Learning, Deep Learning and Natural Language Processing.'
url:              https://saa1605.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
    - jekyll-paginate
    - jekyll-gist
    - redcarpet
