# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Saaket Agashe
tagline:          'Computer Science student interested in Machine Learning, Deep Learning and Natural Language Processing.'
description:      'Computer Science student interested in Machine Learning, Deep Learning and Natural Language Processing.'
url:              https://saa1605.github.io
baseurl:          /

author:
  name:           'Saaket Agashe'
  url:            saa1605.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/saa1605/saa1605.github.io

plugins:
    - jekyll-paginate
    - jekyll-gist
    - redcarpet
